// Regenerates public/vendor/stars.mjs - a self-contained ESM bundle of @pmndrs/vanilla's Stars class with "three" rewritten to our vendored build. Regenerate: npm install --no-save @pmndrs/vanilla@1.25.0 three@0.185.0 esbuild && node build.mjs

import * as esbuild from "esbuild";
import path from "path";

const OUTFILE = path.resolve("../../public/vendor/stars.mjs");

await esbuild.build({
	entryPoints: ["node_modules/@pmndrs/vanilla/core/Stars.js"],
	bundle: true,
	format: "esm",
	minify: true,
	outfile: OUTFILE,
	banner: {
		js: "// Generated by tools/vendor-stars/build.mjs - see that file before editing this one by hand."
	},
	plugins: [
		{
			name: "single-three-instance",
			setup(build) {
				build.onResolve({ filter: /^three$/ }, () => ({
					path: "./three.module.min.js",
					external: true
				}));
			}
		}
	]
});

console.log("Wrote " + OUTFILE);
