// Regenerates public/vendor/three-globe.mjs - a single self-contained ESM
// bundle of three-globe with the "three" core import left as-is (rewritten
// straight to the relative path our own vendored Three.js build lives at, so
// there's no manual patch step to forget on a version bump) and its unused
// WebGPU/TSL render path stubbed out (see stub-webgpu.mjs/stub-tsl.mjs - that
// path alone is ~2MB in three's own build and MMM-Earth3D never uses it).
//
// Why not vendor the official prebuilt files directly:
// - dist/three-globe.min.js (UMD) is fully self-contained but requires a
//   window.THREE global before it loads, and bundles the unused WebGPU/TSL
//   path anyway (1.28MB vs this build's ~540KB).
// - dist/three-globe.mjs (ESM) is the "real" published module, but it leaves
//   ~17 of three-globe's own npm dependencies (d3-geo, kapsule, tinycolor2,
//   three-slippy-map-globe, three/examples/jsm/* addons, etc.) as unresolved
//   bare imports for a bundler/import-map to handle - vendoring all of those
//   individually would be disproportionate for a globe+atmosphere+clouds+
//   day/night feature set.
//
// This script bundles that same ESM entry point ourselves, inlining
// everything except the "three" core import, so the output is a flat file
// loadable exactly like every other file under public/vendor/.
//
// Regenerate with (from this directory):
//   npm install --no-save three-globe@^2.45 three@0.185.0 esbuild
//   node build.mjs

import * as esbuild from "esbuild";
import path from "path";

const OUTFILE = path.resolve("../../public/vendor/three-globe.mjs");

await esbuild.build({
	entryPoints: ["node_modules/three-globe/dist/three-globe.mjs"],
	bundle: true,
	format: "esm",
	minify: true,
	outfile: OUTFILE,
	banner: {
		js: "// Generated by tools/vendor-three-globe/build.mjs - see that file before editing this one by hand."
	},
	plugins: [
		{
			name: "single-three-instance",
			setup(build) {
				// Exact specifier "three" only (not its subpaths, e.g.
				// "three/examples/jsm/..." below, which should stay bundled in -
				// they're small utility addons, harmless to inline even unused).
				// Rewritten straight to the relative vendor path so the emitted
				// file needs no post-build patch.
				build.onResolve({ filter: /^three$/ }, () => ({
					path: "./three.module.min.js",
					external: true
				}));
				build.onResolve({ filter: /^three\/webgpu$/ }, () => ({
					path: path.resolve("stub-webgpu.mjs")
				}));
				build.onResolve({ filter: /^three\/tsl$/ }, () => ({
					path: path.resolve("stub-tsl.mjs")
				}));
			}
		}
	]
});

console.log("Wrote " + OUTFILE);
